[package]
name = "djb_hash"
version = "0.1.0"
authors = ["Michael Cummings <mgcummings@yahoo.com>"]
description = "Rust library of commonly used Daniel J. Bernstein style hash functions."

[dependencies]
